"""
NEXORA Building Intelligence Platform - Recommendation Endpoints
GET /recommendations
GET /recommendations/{recommendation_id}
"""

from typing import List
from fastapi import APIRouter, HTTPException, status

from backend.api.schemas import RecommendationResponse
from backend.api.state import service

router = APIRouter(tags=["Recommendations"])


@router.get(
    "/recommendations",
    response_model=List[RecommendationResponse],
    summary="List active building recommendations generated by the ML & Decision Engine",
)
def get_recommendations() -> List[RecommendationResponse]:
    """
    Returns recommendations generated via closed-loop ML evaluation and Safety Gate constraints:
    - Recommendation ID (e.g. rec-z04-141500)
    - Target Zone (e.g. Z04-CSB)
    - Status (PENDING_APPROVAL)
    - Action (HVAC_SETBACK_LIGHTING_DIM)
    - Predicted load reduction kW
    - Safety checks passed / total (5/5)
    - Confidence score %
    - Provenance ("SIMULATED")
    """
    recs = service.get_recommendations()
    return [RecommendationResponse(**r) for r in recs]


@router.get(
    "/recommendations/{recommendation_id}",
    response_model=RecommendationResponse,
    summary="Get single recommendation by ID",
)
def get_recommendation(recommendation_id: str) -> RecommendationResponse:
    """Returns detailed recommendation object by unique ID."""
    rec = service.get_recommendation(recommendation_id)
    if not rec:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Recommendation '{recommendation_id}' not found.",
        )
    return RecommendationResponse(**rec)
